Repository dnd-side-project/dnd-13th-4-backend, pull requests merged in 2025-08, with the labels that each got.

#22 chore: Spotless 설정
  .script/pre-commit
  build.gradle
  src/main/java/com/example/wini/WiniApplication.java
  src/test/java/com/example/wini/WiniApplicationTests.java
Labels: ⚙️ chore

#28 feat: 공동 응답 객체
  src/main/java/com/example/wini/global/response/ApiResponse.java
Labels: ✨ feature

#30 feat: 마음쪽지 상세 조회
  build.gradle
  src/main/java/com/example/wini/domain/note/controller/NoteController.java
  src/main/java/com/example/wini/domain/note/domain/Note.java
  src/main/java/com/example/wini/domain/note/dto/response/NoteResponse.java
  src/main/java/com/example/wini/domain/note/repository/NoteRepository.java
  src/main/java/com/example/wini/domain/note/service/NoteService.java
  src/main/java/com/example/wini/global/error/exception/ErrorCode.java
  src/main/resources/application-dev.yml
  src/main/resources/application-h2.yml
  src/main/resources/application-swagger.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ feature

#33 feat: 오늘의 쪽지 리스트 조회
  src/main/java/com/example/wini/domain/note/controller/NoteController.java
  src/main/java/com/example/wini/domain/note/repository/NoteCustomRepository.java
  src/main/java/com/example/wini/domain/note/repository/NoteCustomRepositoryImpl.java
  src/main/java/com/example/wini/domain/note/service/NoteService.java
Labels: ✨ feature

#48 chore: mysql 연결
  build.gradle
  src/main/resources/application-mysql.yml
  src/main/resources/application.yml
Labels: ⚙️ chore

#45 feat: 내 상태 수정
  src/main/java/com/example/wini/domain/member/controller/MemberController.java
  src/main/java/com/example/wini/domain/member/domain/Member.java
  src/main/java/com/example/wini/domain/member/dto/common/ReservedTimeInfo.java
  src/main/java/com/example/wini/domain/member/dto/request/MemberStatusUpdateRequest.java
  src/main/java/com/example/wini/domain/member/repository/MemberCustomRepository.java
  src/main/java/com/example/wini/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/com/example/wini/domain/member/repository/StatusRepository.java
  src/main/java/com/example/wini/domain/member/service/MemberService.java
  src/main/java/com/example/wini/global/error/exception/ErrorCode.java
Labels: ✨ feature, 🥈 P2

#49 feat: 상태 리스트 조회
  src/main/java/com/example/wini/domain/member/controller/StatusController.java
  src/main/java/com/example/wini/domain/member/dto/response/StatusResponse.java
  src/main/java/com/example/wini/domain/member/service/StatusService.java
Labels: ✨ feature, 🥈 P2

#51 feat: 감정 리스트 조회
  src/main/java/com/example/wini/domain/note/domain/Note.java
  src/main/java/com/example/wini/domain/note/dto/response/NoteResponse.java
  src/main/java/com/example/wini/domain/note/repository/NoteCustomRepository.java
  src/main/java/com/example/wini/domain/note/repository/NoteCustomRepositoryImpl.java
  src/main/java/com/example/wini/domain/note/service/NoteService.java
  src/main/java/com/example/wini/domain/template/controller/TemplateController.java
  src/main/java/com/example/wini/domain/template/domain/Emotion.java
  src/main/java/com/example/wini/domain/template/domain/EmotionType.java
  src/main/java/com/example/wini/domain/template/dto/response/EmotionResponse.java
  src/main/java/com/example/wini/domain/template/repository/EmotionRepository.java
  src/main/java/com/example/wini/domain/template/service/EmotionService.java
  src/main/java/com/example/wini/global/error/exception/ErrorCode.java
  src/main/resources/application-dev.yml
Labels: ✨ feature

#53 feat: 상황 리스트 조회
  src/main/java/com/example/wini/domain/note/domain/Note.java
  src/main/java/com/example/wini/domain/note/dto/response/NoteResponse.java
  src/main/java/com/example/wini/domain/note/repository/NoteCustomRepository.java
  src/main/java/com/example/wini/domain/note/repository/NoteCustomRepositoryImpl.java
  src/main/java/com/example/wini/domain/note/service/NoteService.java
  src/main/java/com/example/wini/domain/template/controller/TemplateController.java
  src/main/java/com/example/wini/domain/template/domain/Situation.java
  src/main/java/com/example/wini/domain/template/dto/response/SituationResponse.java
  src/main/java/com/example/wini/domain/template/repository/SituationRepository.java
  src/main/java/com/example/wini/domain/template/service/SituationService.java
  src/main/java/com/example/wini/global/error/exception/ErrorCode.java
Labels: ✨ feature

#58 feat: 초대코드 입력
  src/main/java/com/example/wini/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/com/example/wini/domain/room/controller/RoomController.java
  src/main/java/com/example/wini/domain/room/dto/request/RoomJoinRequest.java
  src/main/java/com/example/wini/domain/room/repository/MemberRoomRepository.java
  src/main/java/com/example/wini/domain/room/repository/RoomCustomRepository.java
  src/main/java/com/example/wini/domain/room/repository/RoomCustomRepositoryImpl.java
  src/main/java/com/example/wini/domain/room/service/RoomService.java
  src/main/java/com/example/wini/global/common/constant/RoomConstants.java
  src/main/java/com/example/wini/global/config/JpaAuditingConfig.java
  src/main/java/com/example/wini/global/error/exception/ErrorCode.java
  src/main/resources/application-dev.yml
Labels: ✨ feature, 🥈 P2

#62 feat: 푸시 알림
  .gitignore
  build.gradle
  src/main/java/com/example/wini/domain/member/repository/MemberCustomRepository.java
  src/main/java/com/example/wini/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/com/example/wini/domain/member/service/MemberService.java
  src/main/java/com/example/wini/domain/notification/controller/FirebaseTokenController.java
  src/main/java/com/example/wini/domain/notification/domain/FirebaseToken.java
  src/main/java/com/example/wini/domain/notification/domain/NotificationType.java
  src/main/java/com/example/wini/domain/notification/dto/request/FirebaseTokenSaveRequest.java
  src/main/java/com/example/wini/domain/notification/event/NotificationEvent.java
  src/main/java/com/example/wini/domain/notification/event/NotificationEventListener.java
  src/main/java/com/example/wini/domain/notification/repository/FirebaseTokenRepository.java
  src/main/java/com/example/wini/domain/notification/sender/NotificationSender.java
  src/main/java/com/example/wini/domain/notification/service/FirebaseTokenService.java
  src/main/java/com/example/wini/domain/room/service/RoomService.java
  src/main/java/com/example/wini/global/config/AsyncConfig.java
  src/main/java/com/example/wini/global/config/FirebaseConfig.java
  src/main/java/com/example/wini/global/error/GlobalExceptionHandler.java
  src/main/java/com/example/wini/global/error/exception/ErrorCode.java
  src/main/java/com/example/wini/infra/fcm/client/FcmClient.java
  src/main/java/com/example/wini/infra/fcm/converter/FcmMessageConverter.java
  src/main/java/com/example/wini/infra/fcm/dto/FcmMessageRequest.java
  src/main/resources/application-firebase.yml
  src/main/resources/application.yml
  src/test/java/com/example/wini/WiniApplicationTests.java
  src/test/java/com/example/wini/domain/notification/sender/TestNotificationSender.java
Labels: ✨ feature, 🥈 P2

#65 feat: 카카오 로그인
  .github/workflows/java_ci_build.yml
  build.gradle
  src/main/java/com/example/wini/domain/auth/controller/AuthController.java
  src/main/java/com/example/wini/domain/auth/controller/RefreshTokenController.java
  src/main/java/com/example/wini/domain/auth/domain/RefreshToken.java
  src/main/java/com/example/wini/domain/auth/dto/common/OauthMemberInfo.java
  src/main/java/com/example/wini/domain/auth/dto/response/TokenResponse.java
  src/main/java/com/example/wini/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/example/wini/domain/auth/service/AuthService.java
  src/main/java/com/example/wini/domain/auth/service/RefreshTokenService.java
  src/main/java/com/example/wini/domain/auth/service/TokenService.java
  src/main/java/com/example/wini/domain/common/annotation/Auth.java
  src/main/java/com/example/wini/domain/common/util/MemberUtil.java
  src/main/java/com/example/wini/domain/member/controller/MemberController.java
  src/main/java/com/example/wini/domain/member/domain/Member.java
  src/main/java/com/example/wini/domain/member/repository/MemberRepository.java
  src/main/java/com/example/wini/domain/member/service/MemberService.java
  src/main/java/com/example/wini/domain/notification/controller/FirebaseTokenController.java
  src/main/java/com/example/wini/domain/notification/domain/NotificationType.java
  src/main/java/com/example/wini/domain/notification/service/FirebaseTokenService.java
  src/main/java/com/example/wini/domain/room/controller/RoomController.java
  src/main/java/com/example/wini/domain/room/service/RoomService.java
  src/main/java/com/example/wini/global/common/constant/OauthConstants.java
  src/main/java/com/example/wini/global/common/constant/SecurityConstants.java
  src/main/java/com/example/wini/global/config/CacheConfig.java
  src/main/java/com/example/wini/global/config/JpaAuditingConfig.java
  src/main/java/com/example/wini/global/config/RestClientConfig.java
  src/main/java/com/example/wini/global/config/SecurityConfig.java
  src/main/java/com/example/wini/global/config/SwaggerConfig.java
  src/main/java/com/example/wini/global/error/exception/ErrorCode.java
  src/main/java/com/example/wini/global/security/AuthMember.java
  src/main/java/com/example/wini/global/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/wini/global/security/JwtAuthenticationException.java
  src/main/java/com/example/wini/global/security/JwtAuthenticationFilter.java
  src/main/java/com/example/wini/global/security/JwtProvider.java
  src/main/java/com/example/wini/infra/kakao/client/KakaoClient.java
  src/main/java/com/example/wini/infra/kakao/dto/KakaoAccount.java
  src/main/java/com/example/wini/infra/kakao/dto/KakaoProfile.java
  src/main/java/com/example/wini/infra/kakao/dto/KakaoTokenResponse.java
  src/main/java/com/example/wini/infra/kakao/dto/KakaoUser.java
  src/main/resources/application-dev.yml
  src/main/resources/application-jwt.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
  src/test/java/com/example/wini/WiniApplicationTests.java
  src/test/java/com/example/wini/global/config/TestConfig.java
  src/test/resources/application-test.yml
Labels: ✨ feature, 🥉 P3

#77 feat: 룸메 정보 조회, 내 정보 조회
  src/main/java/com/example/wini/domain/member/controller/MemberController.java
  src/main/java/com/example/wini/domain/member/dto/query/MateInfoQuery.java
  src/main/java/com/example/wini/domain/member/dto/response/MateResponse.java
  src/main/java/com/example/wini/domain/member/dto/response/MemberResponse.java
  src/main/java/com/example/wini/domain/member/repository/MemberCustomRepository.java
  src/main/java/com/example/wini/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/com/example/wini/domain/member/service/MemberService.java
Labels: ✨ feature, 🥈 P2

#82 fix: 행동 조회 시 발생하는 오류
  src/main/java/com/example/wini/global/config/QuerydslConfig.java
Labels: 🐛 fix

#85 feat: 감정 엔티티에 용도별 이미지 url 추가
  src/main/java/com/example/wini/domain/template/domain/Emotion.java
  src/main/java/com/example/wini/domain/template/domain/EmotionType.java
  src/main/java/com/example/wini/domain/template/dto/response/EmotionResponse.java
Labels: ✨ feature

#86 feat: 쪽지 엔티티에 인증된 사용자 연결
  src/main/java/com/example/wini/domain/log/service/LogService.java
  src/main/java/com/example/wini/domain/note/domain/Note.java
  src/main/java/com/example/wini/domain/note/dto/response/NoteResponse.java
  src/main/java/com/example/wini/domain/note/repository/NoteCustomRepository.java
  src/main/java/com/example/wini/domain/note/repository/NoteCustomRepositoryImpl.java
  src/main/java/com/example/wini/domain/note/service/NoteService.java
  src/main/java/com/example/wini/global/error/exception/ErrorCode.java
Labels: ✨ feature

#90 feat: 헬스체크
  src/main/java/com/example/wini/global/common/constant/SecurityConstants.java
  src/main/java/com/example/wini/global/controller/HealthCheckController.java
Labels: ✨ feature, 🥇 P1

#91 feat: 저장된 쪽지에 정렬기준 추가
  src/main/java/com/example/wini/domain/note/controller/NoteController.java
  src/main/java/com/example/wini/domain/note/domain/SortOrder.java
  src/main/java/com/example/wini/domain/note/dto/response/SimpleNoteResponse.java
  src/main/java/com/example/wini/domain/note/repository/NoteCustomRepository.java
  src/main/java/com/example/wini/domain/note/repository/NoteCustomRepositoryImpl.java
  src/main/java/com/example/wini/domain/note/service/NoteService.java
  src/main/java/com/example/wini/global/error/exception/ErrorCode.java
Labels: ✨ feature

#98 feat: 상태 알림에 상태 텍스트 추가
  src/main/java/com/example/wini/domain/member/service/MemberService.java
  src/main/java/com/example/wini/domain/notification/domain/NotificationType.java
  src/main/java/com/example/wini/domain/notification/event/NotificationEvent.java
  src/main/java/com/example/wini/domain/notification/service/FirebaseTokenService.java
  src/main/java/com/example/wini/infra/fcm/client/FcmClient.java
  src/main/java/com/example/wini/infra/fcm/dto/FcmMessageRequest.java
Labels: ✨ feature, 🥉 P3

#95 fix: 나의 성장 조회시 발생하는 오류
  build.gradle
  src/main/java/com/example/wini/domain/log/dto/response/ActionChange.java
  src/main/java/com/example/wini/domain/log/dto/response/SimpleActionChange.java
  src/main/java/com/example/wini/domain/note/repository/NoteCustomRepositoryImpl.java
Labels: 🐛 fix
